<?php
$page_title = "ตั้งค่าร้านค้า";
require_once __DIR__ . "/../includes/config.php";
require_once __DIR__ . "/../includes/auth.php";

$ver = time();
ob_start();
?>

<div class="container-fluid p-4">
    <div class="d-flex justify-content-between align-items-center mb-4">
        <h2 class="mb-0"><i data-lucide="settings" class="me-2"></i>ตั้งค่าร้านค้า</h2>
    </div>

    <form id="shopSettingsForm" enctype="multipart/form-data">
        <input type="hidden" name="shop_id" value="1">
        
        <div class="row">
            <!-- Left Column: General Settings -->
            <div class="col-md-4">
                <div class="card shadow-sm mb-4">
                    <div class="card-header bg-white py-3">
                        <h5 class="mb-0 fw-bold">ข้อมูลทั่วไป</h5>
                    </div>
                    <div class="card-body text-center">
                        <div class="mb-3">
                            <label class="form-label d-block fw-bold">โลโก้ร้านค้า</label>
                            <div class="position-relative d-inline-block">
                                <img id="logoPreview" src="<?= ADMIN_ASSETS ?>/images/placeholder.png" 
                                     class="rounded border shadow-sm mb-2" 
                                     style="width: 150px; height: 150px; object-fit: contain; background: #f8f9fa;">
                                <div class="position-absolute bottom-0 end-0">
                                    <label for="shop_logo" class="btn btn-sm btn-primary rounded-circle" style="width: 32px; height: 32px; padding: 0; display: flex; align-items: center; justify-content: center; cursor: pointer;">
                                        <i data-lucide="camera" style="width: 16px; height: 16px;"></i>
                                    </label>
                                    <input type="file" id="shop_logo" name="shop_logo" class="d-none" accept="image/*" onchange="previewLogo(this)">
                                </div>
                            </div>
                        </div>

                        <div class="text-start">
                            <div class="mb-3">
                                <label class="form-label">เบอร์โทรศัพท์</label>
                                <input type="text" class="form-control" name="shop_phone" id="shop_phone">
                            </div>
                            <div class="mb-3">
                                <label class="form-label">อีเมล</label>
                                <input type="email" class="form-control" name="shop_email" id="shop_email">
                            </div>
                            <div class="mb-3">
                                <label class="form-label">เลขประจำตัวผู้เสียภาษี</label>
                                <input type="text" class="form-control" name="shop_tax_id" id="shop_tax_id">
                            </div>
                        </div>
                    </div>
                </div>
                
                <button type="submit" class="btn btn-primary w-100 py-2 fw-bold">
                    <i data-lucide="save" class="me-2"></i>บันทึกการตั้งค่า
                </button>
            </div>

            <!-- Right Column: Multi-language Address -->
            <div class="col-md-8">
                <div class="card shadow-sm">
                    <div class="card-header bg-white py-3 d-flex justify-content-between align-items-center">
                        <h5 class="mb-0 fw-bold">ที่อยู่ร้านค้า (6 ภาษา)</h5>
                        <!-- Language Tabs -->
                        <ul class="nav nav-pills card-header-pills" id="langTabs" role="tablist">
                            <!-- Tabs will be generated by JS -->
                        </ul>
                    </div>
                    <div class="card-body">
                        <div class="tab-content" id="langTabContent">
                            <!-- Tab panes will be generated by JS -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

<script>
const ADMIN_URL = '<?= ADMIN_URL ?>';
const ROOT_URL = '<?= ROOT_URL ?>';
</script>
<script src="<?= ADMIN_ASSETS ?>/js/language-tabs.js?v=<?= $ver ?>"></script>
<script src="<?= ADMIN_ASSETS ?>/js/shop_settings.js?v=<?= $ver ?>"></script>

<?php 
$content = ob_get_clean();
require_once __DIR__ . "/../includes/layout.php"; 
?>
